version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true
  run:
    desc: Run the game in dev mode
    cmds:
      - cargo run --example main --features bevy/dynamic_linking
    silent: true
  run-release:
    desc: Run the game in release mode
    cmds:
      - cargo run --example main --release
    silent: true
  build-dev:
    desc: Build the game in dev mode
    cmds:
      - cargo build --example main --features bevy/dynamic_linking
    silent: true
  build-release:
    desc: Build the game in release mode
    cmds:
      - cargo build --example main --release
    silent: true
  test:
    desc: Run tests
    cmds:
      - cargo test --example main
    silent: true
